config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'tops#index'
  devise_for :users, controllers: { :registrations => "users/registrations" }
  resources :reviews
  resources :stylists
  resources :seekers 
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    
  has_many :messages, dependent: :destroy
    
  validates_uniqueness_of :sender_id, scope: :recipient_id
   
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
    
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :seeker
  belongs_to :stylist
end

app/models/seeker.rb
class Seeker < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews, dependent: :destroy
  enum gender: { man: 0, woman: 1}
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, numericality: true, uniqueness: true
  ratyrate_rater
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews, dependent: :destroy
  enum gender: { man: 0, woman: 1}
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, numericality: true, uniqueness: true
  ratyrate_rateable "clothes"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_one :seeker, dependent: :destroy
  has_one :stylist, dependent: :destroy
  acts_as_paranoid
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  layout 'review'
  before_action :set_review, only: [:edit, :update, :show, :destroy]
  
  def index
    @reviews = Review.all
  end
  
  def new
   @review = Review.new(stylist_id: params[:stylist_id])
  #  binding.irb
  end
  
  def create
    @review = current_user.seeker.reviews.create(review_params)
    # binding.irb
    if @review.save
      redirect_to reviews_path
    else
      render :new
    end
    # binding.irb
  end
  
  def edit
  end
  
  def update
    if @review.update(review_params)
      redirect_to reviews_path
    else
      render :edit
    end
  end
  
  def destroy
    @review.destroy
    redirect_to reviews_path
  end
    
  private
  def review_params
    params.require(:review).permit(:id, :title, :comment, :seeker_id, :stylist_id)
  end

  def set_review
    @review = current_user.seeker.reviews.find_by(id: params[:id])
  end
end

app/controllers/seekers_controller.rb
class SeekersController < ApplicationController
  layout 'seeker'
  before_action :set_seeker, only: [:edit, :show, :update]
  def index
    @q = Seeker.ransack(params[:q])
    @seekers = @q.result(distinct: true)
  end
  
  def new
    @seeker = Seeker.new
  end
  
  def create
    @seeker = Seeker.new(seeker_params)
    @seeker.user_id = current_user.id
    if @seeker.save
      redirect_to seeker_path(@seeker.id)
    else
      render :new
    end
  end

  def show
    @users = User.all
  end
  
  def edit
  end

  def update
    if @seeker.update(seeker_params)
      redirect_to seeker_path(@seeker)
    else
      render :edit
    end
  end

  private
  def seeker_params
    params.require(:seeker).permit(:id, :name, :icon, :content, :address, :age, :gender, :phone_number, :user_id)
  end

  def set_seeker
    @seeker = Seeker.find(params[:id])
  end
end

app/controllers/stylists_controller.rb
class StylistsController < ApplicationController
  layout 'stylist'
  before_action :set_stylist, only: [:edit, :show, :update]
  def index
    @q = Stylist.ransack(params[:q])
    @stylists = @q.result(distinct: true)
  end
  
  def new
    @stylist = Stylist.new
  end
  
  def create
    # binding.irb
    @stylist = Stylist.new(stylist_params)
    @stylist.user_id = current_user.id
    # binding.irb
    if @stylist.save
      redirect_to stylist_path(@stylist.id)
    else
      render :new
    end
  end

  def show
    # binding.irb
  end
  
  def edit
  end

  def update
    if @stylist.update(stylist_params)
      redirect_to stylist_path(user.id)
    else
      render :edit
    end
  end

  private
  def stylist_params
    params.require(:stylist).permit(:id, :adviser, :name, :icon, :content, :clothes_image, :address, :age, :gender, :phone_number, :user_id)
  end

  def set_stylist
    @stylist = Stylist.find(params[:id])
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/stylists/_form.html.erb
<%= form_with(model: @stylist, url: stylists_path, local: true) do |f| %>
 
  <div class="field">
    <%= f.label :氏名 %><br />
    <%= f.text_field :name %>
  </div>
 
  <div class="field">
    <%= f.label :住所 %><br />
    <%= f.text_field :address %>
  </div>
  <div class="field">
    <%= f.label :TEL %><br />
    <%= f.text_field :phone_number %>
  </div>
  <div class="field">
    <%= f.label :年齢 %><br />
    <%= select_tag(:age, options_for_select((18..50).to_a)) %>
  </div>  
  <div class="field">
    <%= f.label :年齢を非表示にする %>
    <%= f.check_box :hide_age %> 
    </div> 
  <div class="field">
    <%= f.label :性別 %><br />
    <%= f.label :男  %>
    <%= f.radio_button :gender, :man %>
    <%= f.label :女  %>
    <%= f.radio_button :gender, :woman %>
  </div>
  <div class="field">
      <%= f.label :性別を非表示にする %>
      <%= f.check_box :hide_gender %>
    </div> 
  　<div class="field">
      <%= f.label :プロフィール写真 %> 
      <%= f.file_field :icon %>　
      <%= f.hidden_field :id %>
    </div>
    <div class="field">
      <%= f.label :スタイリストとしてのアピールポイント %>
      <%= f.text_area :content %>
    </div>
  
    <div class="actions">
      <%= f.submit %>
    </div>
    
<% end %>

app/views/stylists/edit.html.erb
<h1>プロフィールを作成する</h1>

<%= render 'form' %>

app/views/stylists/index.html.erb
<h1>スタイリスト一覧</h1>
<%= search_form_for @q do |f| %>
  <%= f.label :content, "Keyword" %>
  <%= f.search_field :content_cont %>

  <%= f.label :age %>
  <%= f.number_field :age_gteq, in: 10..50 %>以上〜
  <%= f.number_field :age_lt, min: 10, max: 50 %>未満

  <!--ここから追加-->
  <%= f.label :gender %>
　<%= f.radio_button :gender_eq, '', {:checked => true} %>指定なし
  <%= f.radio_button :gender_eq, 1 %>男性
  <%= f.radio_button :gender_eq, 2 %>女性
  <!--ここまで追加-->

  <%= f.submit "検索" %>
<% end %>
<table>
<tr>
  <th>プロフィール写真<th>
  <th>名前<th>
  <th>年齢<th>
  <th>性別<th>
  <th>自己紹介・経歴<th>
</tr>
<% @stylists.each do |stylist| %>
  <tr>
    <td><%= stylist.name %></td>
    <td><%= stylist.age %></td>
    <td><%= stylist.gender %></td>
    <td><%= stylist.content %></td>
    <td><%= link_to '詳細を見る', stylist_path(stylist.id) %>
  </tr>
<% end %>
</table>

app/views/stylists/new.html.erb
<h1>プロフィールを作成する</h1>

<%= render 'form' %>

app/views/stylists/show.html.erb
<h1>プロフィール画面</h1>

<%= @stylist.user.nickname %>
<%= @stylist.gender %>
<%= @stylist.age %>

  
<% unless current_user.adviser? %>
<%= link_to 'メッセージを送る', conversations_path(sender_id: current_user.id, recipient_id: @stylist.user.id), method: :post %>
<%= link_to '評価する', new_review_path(stylist_id: @stylist.id) %>
<% end %>

<h4><%= @stylist.user.nickname %>さんのレビュー一覧</h4>
<table>
  <tr>
    <th>タイトル</th>
    <th>レビュー</th>
  </tr>
  <% @stylist.reviews.each do |review| %>
  <tr>
    <td><%= review.title %></td>
    <td><%= review.comment %></td>
  </tr>
  <% end %>
</table>