config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  root 'tops#index'
  devise_for :users, controllers: { :registrations => "users/registrations" }
  resources :reviews
  resources :stylists
  resources :seekers 
  resources :conversations do
    resources :messages
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/average_cache.rb
class AverageCache < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true
end

app/models/conversation.rb
class Conversation < ApplicationRecord
  belongs_to :sender, foreign_key: :sender_id, class_name: 'User'
  belongs_to :recipient, foreign_key: :recipient_id, class_name: 'User'
    
  has_many :messages, dependent: :destroy
    
  validates_uniqueness_of :sender_id, scope: :recipient_id
   
  scope :between, -> (sender_id,recipient_id) do
    where("(conversations.sender_id = ? AND conversations.recipient_id =?) OR (conversations.sender_id = ? AND  conversations.recipient_id =?)", sender_id,recipient_id, recipient_id, sender_id)
  end
    
  def target_user(current_user)
    if sender_id == current_user.id
      User.find(recipient_id)
    elsif recipient_id == current_user.id
      User.find(sender_id)
    end
  end
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :conversation
  belongs_to :user
  validates_presence_of :body, :conversation_id, :user_id
  def message_time
    created_at.strftime("%m/%d/%y at %l:%M %p")
  end
end

app/models/overall_average.rb
class OverallAverage < ActiveRecord::Base
  belongs_to :rateable, :polymorphic => true
end

app/models/rate.rb
class Rate < ActiveRecord::Base
  belongs_to :rater, :class_name => "User"
  belongs_to :rateable, :polymorphic => true

  #attr_accessible :rate, :dimension

end

app/models/rating_cache.rb
class RatingCache < ActiveRecord::Base
  belongs_to :cacheable, :polymorphic => true
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :seeker
  belongs_to :stylist
end

app/models/seeker.rb
class Seeker < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews, dependent: :destroy
  enum gender: { man: 0, woman: 1}
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, numericality: true, uniqueness: true
  ratyrate_rater
end

app/models/stylist.rb
class Stylist < ApplicationRecord
  belongs_to :user, optional: true
  has_many :reviews, dependent: :destroy
  enum gender: { man: 0, woman: 1}
  validates :name, presence: true
  validates :address, presence: true
  validates :phone_number, presence: true, numericality: true, uniqueness: true
  ratyrate_rateable "clothes"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  validates :nickname, presence: true
  has_one :seeker, dependent: :destroy
  has_one :stylist, dependent: :destroy
  acts_as_paranoid
end

app/controllers/rater_controller.rb
class RaterController < ApplicationController

  def create
    if user_signed_in?
      obj = params[:klass].classify.constantize.find(params[:id])
      obj.rate params[:score].to_f, current_user, params[:dimension]

      render :json => true
    else
      render :json => false
    end
  end
end

app/controllers/tops_controller.rb
class TopsController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/conversations_helper.rb
module ConversationsHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/seekers_helper.rb
module SeekersHelper
end

app/helpers/stylists_helper.rb
module StylistsHelper
end

app/helpers/tops_helper.rb
module TopsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasuTa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <%= yield %>
  </body>
</html>

app/views/layouts/review.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasuTa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.adviser? %>
      <%= link_to 'マイページ', seeker_path(current_user.seeker.id) %>
      <%= link_to 'マイページ編集', edit_stylist_path(current_user.stylist.id) %> |
      <%= link_to '相談者一覧', seekers_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'マイページ', seeker_path(current_user.seeker.id) %> |
      <%= link_to 'マイページ編集', edit_seeker_path(current_user.seeker.id) %> |
      <%= link_to 'スタイリスト一覧', stylists_path %> |
      <%= link_to 'レビュー管理', reviews_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/seeker.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasuTa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if current_user.adviser? %>
      <%= link_to 'マイページ', stylist_path(current_user.id) %>
      <%= link_to 'マイページ編集', edit_stylist_path(current_user.id) %> |
      <%= link_to '相談者一覧', seekers_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% else %>
      <%= link_to 'マイページ', seeker_path(current_user.id) %> |
      <%= link_to 'マイページ編集', edit_seeker_path(current_user.id) %> |
      <%= link_to 'スタイリスト一覧', stylists_path %> |
      <%= link_to 'レビュー管理', reviews_path %> |
      <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/layouts/stylist.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PasuTa</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% if current_user.adviser? %>
    <%= link_to 'マイページ', stylist_path(current_user.id) %> |
    <%= link_to 'マイページ編集', edit_stylist_path(current_user.id) %> |
    <%= link_to '相談者一覧', seekers_path %> |
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'マイページ', seeker_path(current_user.seeker.id) %> |
    <%= link_to 'マイページ編集', edit_seeker_path(current_user.seeker.id) %> |
    <%= link_to 'スタイリスト一覧', stylists_path %> |
    <%= link_to 'レビュー管理', reviews_path %> |
    <%= link_to "ログアウト", destroy_user_session_path, method: :delete %>
  <% end %>
  <%= yield %>
  </body>
</html>